
GET http://localhost:8000/books/ HTTP/1.1
content-type: application/json

###
GET http://localhost:8000/books/title/Time Shelter HTTP/1.1
content-type: application/json
###
GET http://localhost:8000/books/title/Pyre HTTP/1.1
content-type: application/json
###
GET http://localhost:8000/books/isbn/9781474623025 HTTP/1.1
content-type: application/json
###
GET http://localhost:8000/books/isbn/9781782278627 HTTP/1.1
content-type: application/json
###

GET http://localhost:8000/books/id/?id=2 HTTP/1.1
###

###
POST http://localhost:8000/books/ HTTP/1.1
content-type: application/json

{
    "title": "El Resplandor",
    "isbn" : "111"
}
###
POST http://localhost:8000/books/ HTTP/1.1
content-type: application/json

{
    "title": "El resplandor pdm",
    "isbn" : "111"
}
###
###
POST http://localhost:8000/books/ HTTP/1.1
content-type: application/json

{
    "title": "Ensayo Sobre la Ceguera",
    "isbn" : "222"
}
###

PATCH http://localhost:8000/books/update/?id=4&title=El resplandor pdf HTTP/1.1
content-type: application/json

###

DELETE http://localhost:8000/books/?id=3 HTTP/1.1
content-type: application/json